# Generated by Django 3.0.1 on 2020-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='flag_correlation',
            field=models.BooleanField(default=False),
        ),
    ]
