# Generated by Django 3.0.1 on 2021-05-13 14:57

import Profiler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_file', models.FileField(upload_to='upload/', validators=[Profiler.models.file_size], verbose_name='task_file')),
            ],
        ),
    ]
