# Generated by Django 3.0.1 on 2020-05-26 00:33

import Profiler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupload',
            name='task_file',
            field=models.FileField(upload_to='upload/', validators=[Profiler.models.file_size], verbose_name='task_file'),
        ),
    ]
