# Generated by Django 3.0.1 on 2020-05-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0002_auto_20200525_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskupload',
            name='title',
        ),
    ]
